export const ERRORS = {
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  ITEM_ARCHIVED: "ITEM_ARCHIVED",
  ITEM_NOT_FOUND_OR_ARCHIVED: "ITEM_NOT_FOUND_OR_ARCHIVED",

  INVALID_QUANTITY: "INVALID_QUANTITY",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

  INVALID_OPERATION: "INVALID_OPERATION",

  BALANCE_NOT_FOUND: "BALANCE_NOT_FOUND",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
} as const;

export type SystemErrorType = keyof typeof ERRORS;
